### Ошибка Failed to connect to…

Текст ошибки:

```
Failed to connect to <адрес_хоста>
```

Ошибка возникает, если в качестве имени хоста базы данных было указано `localhost` или другое неверное значение. {{ data-transfer-full-name }} работает из своей сетевой среды (специализированные виртуальные машины в {{ yandex-cloud }}) и не может разрешить имя `localhost` в контексте вашего сервера базы данных. `localhost` всегда указывает на ту же машину, на которой запущена программа, пытающаяся его разрешить.

**Решение:**

1. Если база данных находится на виртуальной машине в {{ yandex-cloud }}, укажите её внутренний IP-адрес или FQDN.

1. Если база данных находится вне {{ yandex-cloud }}, укажите её публичный IP-адрес или FQDN, доступный из интернета.

1. Для кластеров управляемых баз данных в {{ yandex-cloud }} рекомендуется при настройке эндпоинта выбирать **Тип инсталляции** — **Кластер Managed Service for <СУБД>**. В таком случае вы выбираете кластер управляемых БД из списка, а сервис сам определяет актуальные FQDN его хостов.

1. Если вы подключаетесь к кластеру управляемых БД в {{ yandex-cloud }} как к пользовательской инсталляции через FQDN конкретного хоста, убедитесь, что адрес хоста введен корректно.
